apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fx-test-project
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Deel-Playground/fx-test-project
    targetRevision: main
    path: helm
    helm:
      releaseName: fx-test-project
      valueFiles:
        - ../values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: fx-test-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true