export type {
  GroupDashboard,
  LadderBar,
  LadderLayer,
  SandboxUiState,
  ScoreCheck,
  TaskAnswers,
  TaskProgress,
  TaskScoreResult,
  TaskStepId,
  TestAccount,
  TestDashboardLabel,
  TestEntity,
  TestSandboxState,
  TestWorkspace,
} from '@/lib/test-mode/types';
export {
  consolidateEntityBooks,
  computeConsolidatedRisk,
  type ConsolidatedBook,
  type CurrencyRiskRow,
} from '@/lib/test-mode/consolidate';
export {
  assignImpliedCarryFromSwapPoints,
  buildCarryEvolutionBars,
  buildCarryEvolutionLegBars,
  buildCarryEvolutionLegBarsFromSamples,
  buildCarryHorizonSeries,
  buildCashCarryAnalytics,
  buildCashForecastSchedule,
  buildSettleWamScenarios,
  buildShapedSettleWamScenarios,
  optimizeStripShapeAroundWam,
  scoreStripShapeAroundWam,
  resolvedHedgedTotalCarryUsdM,
  preparedLegFwdCarryUsdM,
  preparedStripFwdCarryUsdM,
  preparedBulletFwdCarryUsdM,
  hedgeCashFlowsByMonth,
  withNonCashFxConversion,
  cashInterestPathToHorizon,
  hedgeImprovementBreakdownToT,
  hedgeSettleWamMonths,
  interestBearingCashM,
  monthlyRevenueSeriesLocalM,
  type CarryEvolutionBar,
  type CarryHorizonPoint,
  type CashCarryAnalytics,
  type CashForecastMonthRow,
  type CashInterestLayerRow,
  type HedgeCarryLayerRow,
  type HedgeImprovementBreakdown,
  type OptimizeStripShapeResult,
  type SettleWamScenario,
  type StripShapeLegBar,
  type StripShapeScore,
} from '@/lib/test-mode/cash-carry-analytics';

export {
  buildNordtechWorkspace,
  NORDTECH_ACCOUNT_ENTITY_MAP,
  NORDTECH_ACCOUNTS,
  NORDTECH_DASHBOARDS,
  NORDTECH_ENTITIES,
  NORDTECH_ENTITY_IDS,
} from '@/lib/test-mode/fixtures/nordtech-accounts';
export { NORDTECH_REFERENCE, SCORE_TOLERANCE, withinTolerance } from '@/lib/test-mode/fixtures/nordtech-reference';
export { NORDTECH_VAR } from '@/lib/test-mode/fixtures/nordtech-var';
export { computeStockLadder, largestMismatch } from '@/lib/test-mode/exposure-ladder';
export { computeTaskVar, type VarResult } from '@/lib/test-mode/task-var';
export {
  isVarConfidencePct,
  parseVarConfidencePct,
  VAR_CONFIDENCE_OPTIONS,
  VAR_Z_BY_CONFIDENCE,
  zForConfidence,
  type VarConfidencePct,
} from '@/lib/test-mode/var-confidence';
export {
  DEFAULT_VAR_SETUP,
  EUR_REF_EXPOSURE_M,
  EUR_REF_FLOW_M,
  EUR_REF_STOCK_M,
  FORECAST_PERIOD_OPTIONS,
  FORECAST_UNCERTAINTY_OPTIONS,
  accruedForecastMonths,
  buildupLocalMForBasis,
  computeParametricVarUsdM,
  computeAnalyticsVarUsdM,
  computeForecastUncertaintyVarUsdM,
  computeGrowingExposureVarUsdM,
  accruedPositionFromScheduleM,
  areaEquivalentAverageExposureM,
  averageExposureAtHorizonM,
  averageExposureFromScheduleM,
  monthEndAverageFlatM,
  monthEndAverageFromScheduleM,
  simpleAverageFromScheduleM,
  cumulativeForecastErrorStdM,
  forecastErrorStdForSetupM,
  growingExposurePathFactor,
  growingExposurePathFactorFromSchedule,
  growingVarByHorizonUsdM,
  linearBulletNotionalFromVarUsdM,
  eurRefExposureM,
  expectedEurVarUsdM,
  exposureLocalMForBasis,
  forecastPeriodIdForMonths,
  horizonIdForForecastMonths,
  horizonMonths,
  parseForecastMonths,
  parseForecastUncertainty1m,
  parseVarExposureBasis,
  parseVarHorizonId,
  parseVarSetup,
  setupLabel,
  VAR_EXPOSURE_OPTIONS,
  VAR_PROFILE_OPTIONS,
  VAR_VOL_SOURCE_OPTIONS,
  VAR_AVERAGING_OPTIONS,
  VAR_HORIZON_OPTIONS,
  averageExposureForVaR,
  clampMonthlyVol,
  clampRateVolBpYr,
  monthlyVolForSetup,
  normalizeVarSetup,
  parseMonthlyVol,
  parseRateVolBpYr,
  parseVarAveragingConvention,
  parseVarVolSource,
  parseVolOverrides,
  presetVolForSource,
  serializeRateVolOverride,
  serializeVolOverride,
  volForHorizon,
  volForSource,
  MONTHLY_VOL_MAX,
  MONTHLY_VOL_MIN,
  RATE_VOL_BP_MAX,
  RATE_VOL_BP_MIN,
  type ForecastPeriodId,
  type VarAveragingConvention,
  type VarExposureBasis,
  type VarHorizonId,
  type VarSetup,
  type VarVolSource,
} from '@/lib/test-mode/var-setup';
export {
  pathIntegralE2FromKnots,
  exposureAtKnots,
  buildFlipKnots,
  buildGrowingKnots,
  computeCfarBands,
  type ExposureKnot,
  type CfarBandPoint,
  type CfarBandsResult,
} from '@/lib/test-mode/cfar-drawdown';
export {
  residualKnotsForHedge,
  settlementResidualKnotsForHedge,
  computeHedgeCfarBands,
  RATE_DIFF_VOL_BP_YR,
  DEFAULT_RATE_DIFF_VOL_BP_YR,
  presetRateVolBpYr,
  rateVolBpYrFor,
  residualCfarClosedFormUsdM,
  settlementFundingGapForHedge,
  buildSyntheticHedgeProfile,
  type ResidualHedgeInput,
  type ResidualKnots,
  type CfarRiskBreakdown,
  type ResidualCfarClosedForm,
  type FundingGapPoint,
  type FundingGapResult,
} from '@/lib/test-mode/cfar-residual';
export {
  ensureTask01FxLayers,
  entityHasLocalPositions,
  localReadinessByEntity,
  localsReadyForConsolidation,
  scoreTask01,
} from '@/lib/test-mode/score';
export {
  HEDGE_PATH_BASIS_OPTIONS,
  buildExposurePathPoints,
  buildResidualPath,
  inferHedgePathBasis,
  chartHorizonMonths,
  hedgeBasisNotionalLocalM,
  hedgeBreakevenMonths,
  resolveStripCashSettleMonths,
  resolveBulletCashSettleMonths,
  type StripCashDeliveryAt,
  hedgeRatioForNumber,
  resyncHedgeRatiosToNearestRegime,
  overhedgeGapM,
  pathLevelStats,
  budgetRiskUsdM,
  residualPathVarUsdM,
  resolveChartMonthlyFlows,
  type ExposurePathPoint,
  type HedgePathBasisId,
  type ResidualPathPoint,
} from '@/lib/test-mode/exposure-hedge-path';
export {
  buildRollingHedgeEdges,
  windowFlowSlice,
  buildRollingHedgePathPoints,
  bulletMaturityForForecast,
  edgeMaturityHorizonId,
  bookStripForBasis,
  clearRollingStripForCcy,
  hasRollingStripForCcy,
  stripForwardLegsFromEdges,
  stripMatchesEdges,
  hedgeBreakevensForStrip,
  inferRollingEdgeSizing,
  mergeRollingStripIntoBook,
  sizingForHedgePathBasis,
  needsRollingHedges,
  normalizeStripEndMonths,
  normalizeStripScheduleWeights,
  equalStripScheduleWeights,
  rampStripScheduleWeights,
  shapedStripScheduleWeights,
  pinStripScheduleWeightAt,
  endMonthsFromScheduleWeights,
  scheduleWeightsFromEndMonths,
  notionalWeightsFromAmounts,
  applyStripHedgeShareWeights,
  STRIP_SCHEDULE_WEIGHT_PRESETS,
  packSelectedStripEdges,
  proposeRollingHedgeTickets,
  removeHedgeTicketOrStrip,
  resyncBookedRollingStrips,
  rollingEdgeCount,
  rollingHedgeAtMonth,
  rollingHedgeSmoothAtMonth,
  sizeRollingEdgeLocalM,
  varSetupForHedgeStructure,
  varSetupForPathHedgeRegime,
  type ForecastHedgeStructure,
  type RollingEdgeSizing,
  type RollingHedgeEdge,
  type StripBreakeven,
} from '@/lib/test-mode/rolling-hedge';
export {
  accruedPositionLocalM,
  analyticsOpenExposureLocalM,
  bookedHedgeVarUsdM,
  bookedNotionalLocalM,
  buildStripHedgedVarProfile,
  residualVarFromMismatchUsdM,
  stripAnalyticsWeightedVarUsdM,
  stripCoverLocalM,
  stripNearTermCoverLocalM,
  stripResidualVarAtMonthsUsdM,
  stripTicketsForCcy,
  type StripHedgedVarLeg,
  type StripHedgedVarProfilePoint,
  bookedPositionOffsetsByCcy,
  bookedTicketForCcy,
  buildHedgeVarSummary,
  equalVarLinearHedgeNotionalLocalM,
  buildHedgedVarProfileWithCoverAt,
  equalVarNotionalAtTenureLocalM,
  pathVarCogHedgeLocalM,
  riskBalanceHedgeLocalM,
  isLiveHedgeTicket,
  liveHedgeTickets,
  newHedgeTicketId,
  computeVarOnExposure,
  fxStockExposureLocalM,
  fxHedgeTargetLocalM,
  fxExposureForBasis,
  proposeBookHedge,
  proposeHigherVarHedge,
  aggregateBookedHedges,
  applyBookedHedgePositions,
  applyConsolidatedBookedChange,
  emptyHedgeBook,
  clearPreparedHedgeForCcy,
  setPreparedHedgeForCcy,
  setMarketRatesForCcy,
  fxTableRiskMetrics,
  GROUP_HEDGE_SCOPE,
  overlayRiskFromFxBook,
  riskMetricsFromRows,
  type BookedPositionOffset,
  type CarryProfileSessionV1,
  type EntityHedgeBook,
  type FxTableRiskMetric,
  type HedgeInstrument,
  type HedgeTicket,
  type HedgeTicketStatus,
  type HedgeVarRow,
  type HedgeVarSummary,
  type PreparedHedgeLeg,
  type PreparedHedgeProfile,
  type RowRiskMetric,
} from '@/lib/test-mode/hedge-var';
export {
  classifyNordtechEntity,
  simSeedForEntity,
  TASK01_REQUIRED_ANALYTICAL_LAYERS,
  TASK01_REQUIRED_DECISION_LAYERS,
  TASK01_REQUIRED_FX_INPUTS,
  type EntitySimSeed,
} from '@/lib/test-mode/nordtech-sim-seed';
export {
  STATE_VERSION,
  TEST_GUEST_USER_KEY,
  defaultSandboxUi,
  defaultTaskProgress,
  emptyAnswers,
  loadSandbox,
  markStep,
  mergeHedgeBooksPreservingPrepared,
  newerSandboxState,
  preferWorkspaceSetup,
  workspaceFxProfileCount,
  normalizeSandboxState,
  resetSandbox,
  saveSandbox,
  seedNordtechWorkspace,
  seedSandbox,
} from '@/lib/test-mode/store';
export {
  loadSandboxPersistent,
  persistSandboxRemote,
  resetSandboxPersistent,
  saveSandboxPersistent,
} from '@/lib/test-mode/sandbox-client';
export {
  isTestModeEnabled,
  TEST_GUEST_EMAIL,
  TEST_GUEST_NAME,
} from '@/lib/test-mode/enabled';
