export type {
  GroupDashboard,
  LadderBar,
  LadderLayer,
  SandboxUiState,
  ScoreCheck,
  TaskAnswers,
  TaskProgress,
  TaskScoreResult,
  TaskStepId,
  TestAccount,
  TestDashboardLabel,
  TestEntity,
  TestSandboxState,
  TestWorkspace,
} from '@/lib/test-mode/types';
export {
  consolidateEntityBooks,
  computeConsolidatedRisk,
  type ConsolidatedBook,
  type CurrencyRiskRow,
} from '@/lib/test-mode/consolidate';

export {
  buildNordtechWorkspace,
  NORDTECH_ACCOUNT_ENTITY_MAP,
  NORDTECH_ACCOUNTS,
  NORDTECH_DASHBOARDS,
  NORDTECH_ENTITIES,
  NORDTECH_ENTITY_IDS,
} from '@/lib/test-mode/fixtures/nordtech-accounts';
export { NORDTECH_REFERENCE, SCORE_TOLERANCE, withinTolerance } from '@/lib/test-mode/fixtures/nordtech-reference';
export { NORDTECH_VAR } from '@/lib/test-mode/fixtures/nordtech-var';
export { computeStockLadder, largestMismatch } from '@/lib/test-mode/exposure-ladder';
export { computeTaskVar, type VarResult } from '@/lib/test-mode/task-var';
export {
  isVarConfidencePct,
  parseVarConfidencePct,
  VAR_CONFIDENCE_OPTIONS,
  VAR_Z_BY_CONFIDENCE,
  zForConfidence,
  type VarConfidencePct,
} from '@/lib/test-mode/var-confidence';
export {
  DEFAULT_VAR_SETUP,
  EUR_REF_EXPOSURE_M,
  EUR_REF_FLOW_M,
  EUR_REF_STOCK_M,
  FORECAST_PERIOD_OPTIONS,
  FORECAST_UNCERTAINTY_OPTIONS,
  accruedForecastMonths,
  buildupLocalMForBasis,
  computeParametricVarUsdM,
  computeAnalyticsVarUsdM,
  computeForecastUncertaintyVarUsdM,
  computeGrowingExposureVarUsdM,
  accruedPositionFromScheduleM,
  areaEquivalentAverageExposureM,
  averageExposureAtHorizonM,
  averageExposureFromScheduleM,
  simpleAverageFromScheduleM,
  cumulativeForecastErrorStdM,
  forecastErrorStdForSetupM,
  growingExposurePathFactor,
  growingExposurePathFactorFromSchedule,
  growingVarByHorizonUsdM,
  linearBulletNotionalFromVarUsdM,
  eurRefExposureM,
  expectedEurVarUsdM,
  exposureLocalMForBasis,
  forecastPeriodIdForMonths,
  horizonIdForForecastMonths,
  horizonMonths,
  parseForecastMonths,
  parseForecastUncertainty1m,
  parseVarExposureBasis,
  parseVarHorizonId,
  parseVarSetup,
  setupLabel,
  VAR_EXPOSURE_OPTIONS,
  VAR_HORIZON_OPTIONS,
  volForHorizon,
  type ForecastPeriodId,
  type VarExposureBasis,
  type VarHorizonId,
  type VarSetup,
} from '@/lib/test-mode/var-setup';
export {
  ensureTask01FxLayers,
  entityHasLocalPositions,
  localReadinessByEntity,
  localsReadyForConsolidation,
  scoreTask01,
} from '@/lib/test-mode/score';
export {
  HEDGE_PATH_BASIS_OPTIONS,
  buildExposurePathPoints,
  buildResidualPath,
  inferHedgePathBasis,
  chartHorizonMonths,
  hedgeBasisNotionalLocalM,
  hedgeBreakevenMonths,
  hedgeRatioForNumber,
  overhedgeGapM,
  pathLevelStats,
  residualPathVarUsdM,
  resolveChartMonthlyFlows,
  type ExposurePathPoint,
  type HedgePathBasisId,
  type ResidualPathPoint,
} from '@/lib/test-mode/exposure-hedge-path';
export {
  buildRollingHedgeEdges,
  buildRollingHedgePathPoints,
  hasRollingStripForCcy,
  hedgeBreakevensForStrip,
  mergeRollingStripIntoBook,
  needsRollingHedges,
  proposeRollingHedgeTickets,
  removeHedgeTicketOrStrip,
  rollingEdgeCount,
  rollingHedgeAtMonth,
  sizeRollingEdgeLocalM,
  type RollingEdgeSizing,
  type RollingHedgeEdge,
  type StripBreakeven,
} from '@/lib/test-mode/rolling-hedge';
export {
  accruedPositionLocalM,
  analyticsOpenExposureLocalM,
  bookedNotionalLocalM,
  bookedPositionOffsetsByCcy,
  bookedTicketForCcy,
  buildHedgeVarSummary,
  equalVarLinearHedgeNotionalLocalM,
  isLiveHedgeTicket,
  liveHedgeTickets,
  newHedgeTicketId,
  computeVarOnExposure,
  fxStockExposureLocalM,
  fxHedgeTargetLocalM,
  fxExposureForBasis,
  proposeBookHedge,
  proposeHigherVarHedge,
  aggregateBookedHedges,
  applyBookedHedgePositions,
  applyConsolidatedBookedChange,
  emptyHedgeBook,
  fxTableRiskMetrics,
  GROUP_HEDGE_SCOPE,
  riskMetricsFromRows,
  type BookedPositionOffset,
  type EntityHedgeBook,
  type FxTableRiskMetric,
  type HedgeInstrument,
  type HedgeTicket,
  type HedgeTicketStatus,
  type HedgeVarRow,
  type HedgeVarSummary,
  type RowRiskMetric,
} from '@/lib/test-mode/hedge-var';
export {
  classifyNordtechEntity,
  simSeedForEntity,
  TASK01_REQUIRED_ANALYTICAL_LAYERS,
  TASK01_REQUIRED_DECISION_LAYERS,
  TASK01_REQUIRED_FX_INPUTS,
  type EntitySimSeed,
} from '@/lib/test-mode/nordtech-sim-seed';
export {
  STATE_VERSION,
  TEST_GUEST_USER_KEY,
  defaultSandboxUi,
  defaultTaskProgress,
  emptyAnswers,
  loadSandbox,
  markStep,
  newerSandboxState,
  normalizeSandboxState,
  resetSandbox,
  saveSandbox,
  seedNordtechWorkspace,
  seedSandbox,
} from '@/lib/test-mode/store';
export {
  loadSandboxPersistent,
  persistSandboxRemote,
  resetSandboxPersistent,
  saveSandboxPersistent,
} from '@/lib/test-mode/sandbox-client';
export {
  isTestModeEnabled,
  TEST_GUEST_EMAIL,
  TEST_GUEST_NAME,
} from '@/lib/test-mode/enabled';
