/**
 * mcp-tool-drift.test.ts — the TMS MCP tool catalogue drift check.
 *
 * Every fixture here uses invented tool/module names (fake_tool, FAKE_*). None of them exist in
 * the real treasury repo. That is deliberate: fixtures must never carry real tool names or
 * descriptions, and pinning tests to the real catalogue would make them fail every time a tool
 * is legitimately added or renamed upstream.
 */

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import {
  analyseDrift,
  daysSince,
  formatUnexpectedError,
  getFlagValue,
  missingFrom,
  normalizeDescriptionForCompare,
  parseCatalogueHeader,
  parseCatalogueNameIndex,
  parseCatalogueTools,
  parseRegisteredModuleImports,
  parseToolMetadataBlocks,
  parseTrimmingHints,
  resolveDescription,
  resolveTreasuryRepoPath,
  scanTreasuryRepo,
  unescapeTableCell,
} from './mcp-tool-drift.mjs';

describe('getFlagValue / resolveTreasuryRepoPath', () => {
  it('reads a --flag value form', () => {
    expect(getFlagValue(['--repo', '/tmp/fake'], 'repo')).toBe('/tmp/fake');
  });

  it('reads a --flag=value form', () => {
    expect(getFlagValue(['--repo=/tmp/fake'], 'repo')).toBe('/tmp/fake');
  });

  it('returns null when the flag is absent', () => {
    expect(getFlagValue(['--staleness'], 'repo')).toBeNull();
  });

  it('prefers --repo over TREASURY_REPO', () => {
    expect(resolveTreasuryRepoPath(['--repo', '/from/flag'], { TREASURY_REPO: '/from/env' })).toBe(
      '/from/flag'
    );
  });

  it('falls back to TREASURY_REPO when --repo is absent', () => {
    expect(resolveTreasuryRepoPath([], { TREASURY_REPO: '/from/env' })).toBe('/from/env');
  });

  it('falls back to the hardcoded default when neither is set', () => {
    expect(resolveTreasuryRepoPath([], {})).toBe('/Users/vviital/projects/treasury');
  });
});

describe('parseCatalogueNameIndex', () => {
  it('reads names from the fenced block under the heading', () => {
    const markdown = [
      '## Tool name index',
      '',
      '```',
      'fake_tool_one',
      'fake_tool_two',
      '```',
      '',
      '## How to read this file',
    ].join('\n');
    expect(parseCatalogueNameIndex(markdown)).toEqual(['fake_tool_one', 'fake_tool_two']);
  });

  it('de-duplicates and sorts', () => {
    const markdown = '## Tool name index\n```\nzed_tool\nalpha_tool\nzed_tool\n```\n';
    expect(parseCatalogueNameIndex(markdown)).toEqual(['alpha_tool', 'zed_tool']);
  });

  it('returns empty when the heading is missing', () => {
    expect(parseCatalogueNameIndex('# Nothing here')).toEqual([]);
  });

  it('returns empty when the heading has no fenced block', () => {
    expect(parseCatalogueNameIndex('## Tool name index\nno fence here\n')).toEqual([]);
  });

  it('ignores stray non-identifier lines inside the fence', () => {
    const markdown = '## Tool name index\n```\nfake_tool\n(129 tools)\n```\n';
    expect(parseCatalogueNameIndex(markdown)).toEqual(['fake_tool']);
  });
});

describe('parseCatalogueHeader', () => {
  it('extracts the generation date and read-only count', () => {
    const markdown =
      '> Generated by /fx-sync-mcp-tools on 2026-09-01. Do not hand-edit.\n' +
      '> 181 read-only tools catalogued · 40 mutating tools listed as forbidden\n';
    expect(parseCatalogueHeader(markdown)).toEqual({ generatedOn: '2026-09-01', readOnlyCount: 181 });
  });

  it('returns nulls when the header is absent', () => {
    expect(parseCatalogueHeader('# Empty file')).toEqual({ generatedOn: null, readOnlyCount: null });
  });
});

describe('daysSince', () => {
  it('computes whole days between two dates', () => {
    const now = new Date('2026-09-05T12:00:00.000Z');
    expect(daysSince('2026-09-01', now)).toBe(4);
  });

  it('returns 0 for the same day', () => {
    const now = new Date('2026-09-01T23:00:00.000Z');
    expect(daysSince('2026-09-01', now)).toBe(0);
  });

  it('returns null for an unparseable date', () => {
    expect(daysSince('not-a-date', new Date())).toBeNull();
  });
});

describe('parseTrimmingHints', () => {
  it('extracts a simple single-quoted entry', () => {
    const source = "export const RESPONSE_TRIMMING_HINT = {\n  fakeHint: 'Trim: fields [\"a\"].',\n} as const;";
    expect(parseTrimmingHints(source)).toEqual({ fakeHint: 'Trim: fields ["a"].' });
  });

  it('joins a concatenated multi-line entry', () => {
    const source = [
      'export const RESPONSE_TRIMMING_HINT = {',
      "    fakeHint:",
      "        'Trim: fields [\"a\",\"b\"] ' +",
      "        'or omit [\"c\"].',",
      '} as const;',
    ].join('\n');
    expect(parseTrimmingHints(source).fakeHint).toBe('Trim: fields ["a","b"] or omit ["c"].');
  });

  it('extracts multiple entries', () => {
    const source = [
      'export const RESPONSE_TRIMMING_HINT = {',
      "    fakeOne: 'First hint.',",
      "    fakeTwo: 'Second hint.',",
      '} as const;',
    ].join('\n');
    expect(parseTrimmingHints(source)).toEqual({ fakeOne: 'First hint.', fakeTwo: 'Second hint.' });
  });

  it('returns empty when the object is absent', () => {
    expect(parseTrimmingHints('export const SOMETHING_ELSE = {};')).toEqual({});
  });

  // The real trimming_hints.ts only uses single quotes today, but the value-matching alternation
  // previously had no backtick branch — a hint written as a template literal wouldn't even be
  // recognized as a value by the outer entry pattern, so the whole entry silently failed to
  // match rather than partially matching. Found by an independent Opus 5 review.
  it('extracts a backtick template-literal entry', () => {
    const source = "export const RESPONSE_TRIMMING_HINT = {\n  fakeHint: `Trim: fields [\"a\"].`,\n} as const;";
    expect(parseTrimmingHints(source)).toEqual({ fakeHint: 'Trim: fields ["a"].' });
  });
});

describe('resolveDescription', () => {
  it('joins plain concatenated string literals', () => {
    const raw = "'Fake tool description. ' + 'Second sentence.'";
    expect(resolveDescription(raw, {})).toBe('Fake tool description. Second sentence.');
  });

  // download_vendor_bill_pdf and 69 other real tools (70 of 219, ≈32% — measured directly via
  // `grep -rlP "description:\s*\n?\s*\x60" app/src/mcp/tools/` against the treasury checkout, not
  // guessed) write their description as one backtick template literal instead of concatenated
  // quotes. Missing this left all 70 with an empty description on the first generation pass.
  it('reads a backtick template literal description', () => {
    const raw = '`Fake multi-line description.\n\nSecond paragraph.`';
    expect(resolveDescription(raw, {})).toBe('Fake multi-line description.\n\nSecond paragraph.');
  });

  it('appends a resolved RESPONSE_TRIMMING_HINT reference', () => {
    const raw = "'Fake tool description. ' + RESPONSE_TRIMMING_HINT.fakeHint";
    expect(resolveDescription(raw, { fakeHint: 'Trim: fields ["a"].' })).toBe(
      'Fake tool description. Trim: fields ["a"].'
    );
  });

  it('leaves an unknown hint key silently unresolved rather than throwing', () => {
    const raw = "'Fake tool description. ' + RESPONSE_TRIMMING_HINT.unknownHint";
    expect(resolveDescription(raw, {})).toBe('Fake tool description.');
  });

  // At least 8 real tools (ns_get_vendor_bill.ts and others) write the hint as a template-literal
  // INTERPOLATION inside the backtick description, not as a `+`-concatenated reference. An
  // earlier version of this function only handled the `+` form: it left the literal
  // "${RESPONSE_TRIMMING_HINT.x}" text in place (extracted verbatim by the backtick-literal
  // regex) AND additionally appended a duplicate copy of the resolved hint onto the very end of
  // the whole description, in the wrong position. Found by an independent Opus 5 review.
  it('resolves a ${RESPONSE_TRIMMING_HINT.key} interpolation inside a backtick literal, in place', () => {
    const raw = '`Fake summary.\n\n${RESPONSE_TRIMMING_HINT.fakeHint}`';
    expect(resolveDescription(raw, { fakeHint: 'Trim: fields ["a"].' })).toBe(
      'Fake summary.\n\nTrim: fields ["a"].'
    );
  });

  it('drops an unresolvable ${RESPONSE_TRIMMING_HINT.key} interpolation silently, like the bare form', () => {
    const raw = '`Fake summary. ${RESPONSE_TRIMMING_HINT.unknownHint} End.`';
    expect(resolveDescription(raw, {})).toBe('Fake summary.  End.');
  });
});

describe('parseToolMetadataBlocks', () => {
  it('parses name, description, readOnly, and requiredPermissions', () => {
    const source = [
      "export const metadata: FinanceToolMetadata = {",
      "    name: 'fake_tool',",
      "    title: 'Fake tool',",
      "    description: 'Does a fake thing.',",
      "    requiredPermissions: {fake_resource: 'READ'},",
      "    annotations: {readOnlyHint: true},",
      "};",
    ].join('\n');
    const [tool] = parseToolMetadataBlocks(source, {});
    expect(tool.name).toBe('fake_tool');
    expect(tool.description).toBe('Does a fake thing.');
    expect(tool.readOnly).toBe(true);
    expect(tool.requiredPermissions).toContain('fake_resource');
  });

  it('marks a tool without readOnlyHint as mutating', () => {
    const source = [
      "export const metadata: FinanceToolMetadata = {",
      "    name: 'fake_mutator',",
      "    description: 'Changes a fake thing.',",
      "    requiredPermissions: {fake_resource: 'EDIT'},",
      "};",
    ].join('\n');
    const [tool] = parseToolMetadataBlocks(source, {});
    expect(tool.readOnly).toBe(false);
  });

  it('resolves a concatenated description with a trimming hint', () => {
    const source = [
      "export const metadata: FinanceToolMetadata = {",
      "    name: 'fake_tool',",
      "    description:",
      "        'Does a fake thing. ' +",
      "        RESPONSE_TRIMMING_HINT.fakeHint,",
      "    requiredPermissions: {fake_resource: 'READ'},",
      "    annotations: {readOnlyHint: true},",
      "};",
    ].join('\n');
    const [tool] = parseToolMetadataBlocks(source, { fakeHint: 'Trim: fields ["x"].' });
    expect(tool.description).toBe('Does a fake thing. Trim: fields ["x"].');
  });

  it('returns an empty array for a helper module with no metadata export', () => {
    const source = "export function fakeHelper() { return 1; }";
    expect(parseToolMetadataBlocks(source, {})).toEqual([]);
  });
});

describe('parseRegisteredModuleImports', () => {
  it('resolves only the imports actually referenced in the exported array', () => {
    const source = [
      "import * as fakeToolOne from '../tools/fake_domain/fake_tool_one';",
      "import * as fakeToolTwo from '../tools/fake_domain/fake_tool_two';",
      "import * as fakeToolDisabled from '../tools/fake_domain/fake_tool_disabled';",
      "",
      "export const registeredFinanceToolModules: ToolModule[] = [",
      "    fakeToolOne,",
      "    // fakeToolDisabled, // Disabled: mutation tools deferred for now",
      "    fakeToolTwo,",
      "] as unknown as ToolModule[];",
    ].join('\n');
    const { importedNames, importPathByName } = parseRegisteredModuleImports(source);
    expect([...importedNames].sort()).toEqual(['fakeToolOne', 'fakeToolTwo']);
    expect(importPathByName.get('fakeToolOne')).toBe('../tools/fake_domain/fake_tool_one');
    // Commented-out entries never reach the array body as a bare identifier line, so the
    // disabled tool is correctly excluded even though it is imported.
    expect(importedNames.has('fakeToolDisabled')).toBe(false);
  });

  it('returns empty sets when the array is absent', () => {
    const { importedNames, importPathByName } = parseRegisteredModuleImports('export const X = 1;');
    expect(importedNames.size).toBe(0);
    expect(importPathByName.size).toBe(0);
  });

  // registered_tools.ts is comment-dense (35+ `//` section headers in the real file). Found by
  // an independent Opus 5 review: a whole-line-only regex silently dropped any live entry that
  // didn't fit the exact shape "just a name, optionally followed by a comma, alone on its line" —
  // which would hide a genuinely new registration from drift detection rather than surface it.
  it('picks up a live entry that carries a trailing comment', () => {
    const source = [
      "import * as fakeToolOne from '../tools/fake_domain/fake_tool_one';",
      "",
      "export const registeredFinanceToolModules: ToolModule[] = [",
      "    fakeToolOne, // still live, kept for backwards compatibility",
      "] as unknown as ToolModule[];",
    ].join('\n');
    const { importedNames } = parseRegisteredModuleImports(source);
    expect([...importedNames]).toEqual(['fakeToolOne']);
  });

  it('picks up more than one entry written on the same line', () => {
    const source = [
      "import * as fakeToolOne from '../tools/fake_domain/fake_tool_one';",
      "import * as fakeToolTwo from '../tools/fake_domain/fake_tool_two';",
      "",
      "export const registeredFinanceToolModules: ToolModule[] = [",
      "    fakeToolOne, fakeToolTwo,",
      "] as unknown as ToolModule[];",
    ].join('\n');
    const { importedNames } = parseRegisteredModuleImports(source);
    expect([...importedNames].sort()).toEqual(['fakeToolOne', 'fakeToolTwo']);
  });

  it('does not pull a disabled name out of a comment trailing a real entry', () => {
    const source = [
      "import * as fakeToolOne from '../tools/fake_domain/fake_tool_one';",
      "import * as fakeToolDisabled from '../tools/fake_domain/fake_tool_disabled';",
      "",
      "export const registeredFinanceToolModules: ToolModule[] = [",
      "    fakeToolOne, // fakeToolDisabled would go here once re-enabled",
      "] as unknown as ToolModule[];",
    ].join('\n');
    const { importedNames } = parseRegisteredModuleImports(source);
    expect([...importedNames]).toEqual(['fakeToolOne']);
  });
});

describe('unescapeTableCell', () => {
  // sf_query_subsidiary_account_balance's real description contains `"trandate" | "posting_period"`
  // and `|x|<1e-9` — a literal pipe that the catalogue generator escapes as `\|` so the row
  // still parses as one markdown table cell. Reading it back without reversing that escape
  // reported this tool as changed on every single run, with zero actual drift.
  it('reverses the escaped-pipe markdown table cell convention', () => {
    expect(unescapeTableCell('balanceBasis ("trandate" \\| "posting_period")')).toBe(
      'balanceBasis ("trandate" | "posting_period")'
    );
  });

  it('leaves text with no escaped pipes unchanged', () => {
    expect(unescapeTableCell('Plain description, no pipes.')).toBe('Plain description, no pipes.');
  });
});

describe('normalizeDescriptionForCompare', () => {
  it('collapses newlines and repeated whitespace to single spaces', () => {
    expect(normalizeDescriptionForCompare('Line one.\n\nLine two.   Line three.')).toBe(
      'Line one. Line two. Line three.'
    );
  });

  it('trims leading and trailing whitespace', () => {
    expect(normalizeDescriptionForCompare('  padded  ')).toBe('padded');
  });
});

describe('missingFrom', () => {
  it('returns items in a not present in b', () => {
    expect(missingFrom(['a', 'b', 'c'], ['b'])).toEqual(['a', 'c']);
  });

  it('returns empty when everything is present', () => {
    expect(missingFrom(['a'], ['a', 'b'])).toEqual([]);
  });
});

describe('scanTreasuryRepo — against a fake checkout on disk', () => {
  let tmpDir: string;

  afterEach(() => {
    if (tmpDir) fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  function writeFakeCheckout(files: Record<string, string>): string {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'fx-sync-mcp-tools-test-'));
    for (const [relativePath, content] of Object.entries(files)) {
      const fullPath = path.join(dir, relativePath);
      fs.mkdirSync(path.dirname(fullPath), { recursive: true });
      fs.writeFileSync(fullPath, content, 'utf8');
    }
    return dir;
  }

  it('returns null when registered_tools.ts is absent (not a treasury checkout)', () => {
    tmpDir = writeFakeCheckout({ 'package.json': '{}' });
    expect(scanTreasuryRepo(tmpDir)).toBeNull();
  });

  it('parses a minimal fake checkout end to end', () => {
    tmpDir = writeFakeCheckout({
      'app/src/mcp/lib/registered_tools.ts': [
        "import * as fakeReadOnlyTool from '../tools/fake_domain/fake_read_only_tool';",
        "import * as fakeMutatingTool from '../tools/fake_domain/fake_mutating_tool';",
        "import * as fakeHelper from '../tools/fake_domain/fake_helper';",
        "",
        "export const registeredFinanceToolModules: ToolModule[] = [",
        "    fakeReadOnlyTool,",
        "    fakeMutatingTool,",
        "    fakeHelper,",
        "] as unknown as ToolModule[];",
      ].join('\n'),
      'app/src/mcp/lib/trimming_hints.ts': [
        "export const RESPONSE_TRIMMING_HINT = {",
        "    fakeHint: 'Trim: fields [\"a\"].',",
        "} as const;",
      ].join('\n'),
      'app/src/mcp/tools/fake_domain/fake_read_only_tool.ts': [
        "export const metadata: FinanceToolMetadata = {",
        "    name: 'fake_read_only_tool',",
        "    description: 'Reads a fake thing. ' + RESPONSE_TRIMMING_HINT.fakeHint,",
        "    requiredPermissions: {fake_resource: 'READ'},",
        "    annotations: {readOnlyHint: true},",
        "};",
      ].join('\n'),
      'app/src/mcp/tools/fake_domain/fake_mutating_tool.ts': [
        "export const metadata: FinanceToolMetadata = {",
        "    name: 'fake_mutating_tool',",
        "    description: 'Mutates a fake thing.',",
        "    requiredPermissions: {fake_resource: 'EDIT'},",
        "};",
      ].join('\n'),
      // Helper module: exports no `metadata`, matching lazy_deps.ts / shared_context.ts in the
      // real repo. Must not appear in scan results and must not crash the scan.
      'app/src/mcp/tools/fake_domain/fake_helper.ts': "export function fakeHelperFn() {}",
    });

    const tools = scanTreasuryRepo(tmpDir);
    expect(tools).not.toBeNull();
    expect(tools!.map((t) => t.name).sort()).toEqual(['fake_mutating_tool', 'fake_read_only_tool']);

    const readOnlyTool = tools!.find((t) => t.name === 'fake_read_only_tool')!;
    expect(readOnlyTool.description).toBe('Reads a fake thing. Trim: fields ["a"].');
    expect(readOnlyTool.readOnly).toBe(true);

    const mutatingTool = tools!.find((t) => t.name === 'fake_mutating_tool')!;
    expect(mutatingTool.readOnly).toBe(false);
  });

  it('treats a resolved but unreadable import path as excluded, not a crash', () => {
    tmpDir = writeFakeCheckout({
      'app/src/mcp/lib/registered_tools.ts': [
        "import * as fakeGhostTool from '../tools/fake_domain/fake_ghost_tool';",
        "",
        "export const registeredFinanceToolModules: ToolModule[] = [",
        "    fakeGhostTool,",
        "] as unknown as ToolModule[];",
      ].join('\n'),
      // fake_ghost_tool.ts deliberately not written to disk.
    });
    expect(scanTreasuryRepo(tmpDir)).toEqual([]);
  });
});

describe('analyseDrift', () => {
  function catalogue(names: string[], overrides: { description?: Map<string, string>; readOnly?: Map<string, boolean> } = {}) {
    return {
      names,
      descriptionByName: overrides.description ?? new Map(names.map((n) => [n, `${n} description`])),
      readOnlyByName: overrides.readOnly ?? new Map(names.map((n) => [n, true])),
    };
  }

  it('reports no drift when catalogue and repo match exactly', () => {
    const repoTools = [{ name: 'fake_tool', description: 'fake_tool description', readOnly: true }];
    const result = analyseDrift(catalogue(['fake_tool']), repoTools);
    expect(result.hasDrift).toBe(false);
  });

  it('reports a tool in the repo but not in the catalogue', () => {
    const repoTools = [
      { name: 'fake_tool', description: 'fake_tool description', readOnly: true },
      { name: 'fake_new_tool', description: 'brand new', readOnly: true },
    ];
    const result = analyseDrift(catalogue(['fake_tool']), repoTools);
    expect(result.inRepoNotInCatalogue).toEqual(['fake_new_tool']);
    expect(result.hasDrift).toBe(true);
  });

  it('reports a tool in the catalogue but not in the repo (stale checkout or removed tool)', () => {
    const repoTools = [{ name: 'fake_tool', description: 'fake_tool description', readOnly: true }];
    const result = analyseDrift(catalogue(['fake_tool', 'fake_removed_tool']), repoTools);
    expect(result.inCatalogueNotInRepo).toEqual(['fake_removed_tool']);
    expect(result.hasDrift).toBe(true);
  });

  it('reports a changed description for a tool present in both', () => {
    const repoTools = [{ name: 'fake_tool', description: 'a NEW description', readOnly: true }];
    const result = analyseDrift(catalogue(['fake_tool']), repoTools);
    expect(result.descriptionChanged).toEqual(['fake_tool']);
    expect(result.hasDrift).toBe(true);
  });

  // The catalogue's markdown table cells are single-line (a raw newline breaks a table row), so
  // a multi-paragraph backtick-literal description (several real tools use one, e.g.
  // download_vendor_bill_pdf) is flattened when the table is generated. Without normalizing both
  // sides the same way, every one of those tools would report as "changed" on every run.
  it('does not report drift for a description that differs only in whitespace/newlines', () => {
    const repoTools = [
      { name: 'fake_tool', description: 'Fake summary.\n\nSecond paragraph.  Third.', readOnly: true },
    ];
    const result = analyseDrift(
      catalogue(['fake_tool'], {
        description: new Map([['fake_tool', 'Fake summary. Second paragraph. Third.']]),
      }),
      repoTools
    );
    expect(result.descriptionChanged).toEqual([]);
    expect(result.hasDrift).toBe(false);
  });

  it('reports a tool that flipped from read-only to mutating', () => {
    const repoTools = [{ name: 'fake_tool', description: 'fake_tool description', readOnly: false }];
    const result = analyseDrift(catalogue(['fake_tool']), repoTools);
    expect(result.readOnlyFlagChanged).toEqual(['fake_tool']);
    expect(result.hasDrift).toBe(true);
  });
});

describe('formatUnexpectedError', () => {
  // Verified against a real throwing stand-in script by an independent Opus 5 review: without
  // this wrapper, an unexpected exception printed a full Node stack trace to stderr and exited 1
  // at session start. A SessionStart hook must fail open, never crash-looking, the same principle
  // .claude/hooks/protected-paths.mjs's own header states for its PreToolUse hook.
  it('exits 0 with a friendly message in staleness mode, never a stack trace', () => {
    const result = formatUnexpectedError(new Error('fake failure'), true);
    expect(result.exitCode).toBe(0);
    expect(result.message).not.toContain('at ');
    expect(result.message).toContain('run /fx-sync-mcp-tools');
  });

  it('exits 1 with a SCAN FAILED message in drift mode', () => {
    const result = formatUnexpectedError(new Error('fake failure'), false);
    expect(result.exitCode).toBe(1);
    expect(result.message).toContain('RESULT: SCAN FAILED');
    expect(result.message).toContain('fake failure');
  });

  it('handles a non-Error thrown value without crashing itself', () => {
    const result = formatUnexpectedError('a thrown string, not an Error', true);
    expect(result.exitCode).toBe(0);
    expect(result.message).toContain('run /fx-sync-mcp-tools');
  });
});

describe('parseCatalogueTools', () => {
  it('reads a read-only table row into descriptionByName and readOnlyByName', () => {
    const catalogue = [
      '## Read-only catalogue by domain',
      '',
      '### Fake Domain',
      '',
      '| Tool | Permission | Description |',
      '|---|---|---|',
      "| `fake_read_only_tool` | `fake_resource: 'READ'` | Reads a fake thing. |",
      '',
      '## Mutating tools — never call',
      '',
    ].join('\n');
    const { descriptionByName, readOnlyByName } = parseCatalogueTools(catalogue);
    expect(descriptionByName.get('fake_read_only_tool')).toBe('Reads a fake thing.');
    expect(readOnlyByName.get('fake_read_only_tool')).toBe(true);
  });

  it('reads a mutating table name into readOnlyByName only, never descriptionByName', () => {
    const catalogue = [
      '## Read-only catalogue by domain',
      '',
      '## Mutating tools — never call',
      '',
      '### Fake Domain',
      '',
      '| Tool | Permission |',
      '|---|---|',
      "| `fake_mutating_tool` | `fake_resource: 'CREATE'` |",
      '',
    ].join('\n');
    const { descriptionByName, readOnlyByName } = parseCatalogueTools(catalogue);
    expect(readOnlyByName.get('fake_mutating_tool')).toBe(false);
    expect(descriptionByName.has('fake_mutating_tool')).toBe(false);
  });

  // Found by an independent Opus 5 review, against a real generated catalogue: a whole-file
  // multiline regex let `[^|]*` and a lazy `(.+?)` cross the newline out of a short (2-column)
  // mutating row and into the FOLLOWING row, fabricating a bogus "description" for the first
  // row's tool name out of the second row's content — reported as real drift on
  // `tms_create_financial_account` where none existed. This reproduces that exact shape: a
  // 2-column mutating row immediately followed by another row.
  it('does not fabricate a description for a mutating tool from the row that follows it', () => {
    const catalogue = [
      '## Mutating tools — never call',
      '',
      '### Fake Domain',
      '',
      '| Tool | Permission |',
      '|---|---|',
      "| `fake_mutating_one` | `fake_resource: 'CREATE'` |",
      "| `fake_mutating_two` | `fake_resource: 'EDIT'` |",
      '',
    ].join('\n');
    const { descriptionByName, readOnlyByName } = parseCatalogueTools(catalogue);
    expect(descriptionByName.has('fake_mutating_one')).toBe(false);
    expect(descriptionByName.has('fake_mutating_two')).toBe(false);
    expect(readOnlyByName.get('fake_mutating_one')).toBe(false);
    expect(readOnlyByName.get('fake_mutating_two')).toBe(false);
  });

  it('does not fabricate a description crossing from a mutating row into a following read-only table', () => {
    const catalogue = [
      '## Mutating tools — never call',
      '',
      '### Fake Domain',
      '',
      '| Tool | Permission |',
      '|---|---|',
      "| `fake_mutating_tool` | `fake_resource: 'CREATE'` |",
      '',
      '## Read-only catalogue by domain',
      '',
      '### Fake Domain',
      '',
      '| Tool | Permission | Description |',
      '|---|---|---|',
      "| `fake_read_only_tool` | `fake_resource: 'READ'` | Reads a fake thing. |",
    ].join('\n');
    const { descriptionByName, readOnlyByName } = parseCatalogueTools(catalogue);
    expect(descriptionByName.has('fake_mutating_tool')).toBe(false);
    expect(readOnlyByName.get('fake_mutating_tool')).toBe(false);
    expect(descriptionByName.get('fake_read_only_tool')).toBe('Reads a fake thing.');
  });

  it('unescapes a literal pipe in a description read back from a table row', () => {
    const catalogue = [
      '## Read-only catalogue by domain',
      '',
      '| Tool | Permission | Description |',
      '|---|---|---|',
      "| `fake_tool` | `fake_resource: 'READ'` | balanceBasis (\"a\" \\| \"b\"). |",
    ].join('\n');
    const { descriptionByName } = parseCatalogueTools(catalogue);
    expect(descriptionByName.get('fake_tool')).toBe('balanceBasis ("a" | "b").');
  });

  // Found by an independent Opus 5 review: "Deep reference" has its own 4-column
  // `| Param | Type | Required | Description |` tables, and a PARAMETER row matches the same
  // 3-group tool-row pattern just as well as a real tool row does — it fabricated a bogus
  // descriptionByName entry keyed by a parameter name (`currency`, `limit`, `date`, …) instead of
  // a tool name. Harmless only by coincidence (no parameter happened to share a name with a real
  // tool) until now.
  it('does not treat a Deep reference parameter row as a tool row', () => {
    const catalogue = [
      '## Read-only catalogue by domain',
      '',
      '| Tool | Permission | Description |',
      '|---|---|---|',
      "| `fake_read_only_tool` | `fake_resource: 'READ'` | Reads a fake thing. |",
      '',
      '## Mutating tools — never call',
      '',
      '## Deep reference',
      '',
      '#### `fake_read_only_tool`',
      '',
      'Reads a fake thing.',
      '',
      '| Param | Type | Required | Description |',
      '|---|---|---|---|',
      '| `currency` | string | no | Currency code. |',
    ].join('\n');
    const { descriptionByName } = parseCatalogueTools(catalogue);
    expect(descriptionByName.get('fake_read_only_tool')).toBe('Reads a fake thing.');
    expect(descriptionByName.has('currency')).toBe(false);
  });

  // Found by the same review: `$` without the `m` flag already matches end-of-string OR just
  // before a single trailing newline at the very end of the string. The original lookahead
  // `(?=\n## |\n$)` required an EXTRA explicit `\n` beyond that, so a catalogue whose mutating
  // section is the very last thing in the file — no trailing blank line, no following heading —
  // matched nothing at all, silently losing every mutating classification. That is the more
  // dangerous failure direction: it reports IN SYNC while having verified nothing.
  it('finds mutating tool names when the section is the last thing in the file, with no trailing heading', () => {
    const catalogue = [
      '## Mutating tools — never call',
      '',
      "| `fake_mutating_tool` | `fake_resource: 'CREATE'` |",
    ].join('\n');
    const { readOnlyByName } = parseCatalogueTools(catalogue);
    expect(readOnlyByName.get('fake_mutating_tool')).toBe(false);
  });
});
